In [3]:
import pandas as pd

df = pd.read_csv("data/daily_report.csv")

df

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incidence_Rate,Case-Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2020-10-09 04:23:59,33.939110,67.709953,39616,1470,33058,5088.0,Afghanistan,101.766474,3.710622
1,NaN,NaN,NaN,Albania,2020-10-09 04:23:59,41.153300,20.168300,14899,411,9215,5273.0,Albania,517.721871,2.758574
2,NaN,NaN,NaN,Algeria,2020-10-09 04:23:59,28.033900,1.659600,52658,1783,36958,13917.0,Algeria,120.083803,3.386000
3,NaN,NaN,NaN,Andorra,2020-10-09 04:23:59,42.506300,1.521800,2568,54,1715,799.0,Andorra,3323.626480,2.102804
4,NaN,NaN,NaN,Angola,2020-10-09 04:23:59,-11.202700,17.873900,5958,208,2635,3115.0,Angola,18.128009,3.491104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3950,NaN,NaN,NaN,West Bank and Gaza,2020-10-09 04:23:59,31.952200,35.233200,43256,359,36584,6313.0,West Bank and Gaza,847.921440,0.829943
3951,NaN,NaN,NaN,Western Sahara,2020-10-09 04:23:59,24.215500,-12.885800,10,1,8,1.0,Western Sahara,1.674116,10.000000
3952,NaN,NaN,NaN,Yemen,2020-10-09 04:23:59,15.552727,48.516388,2050,593,1329,128.0,Yemen,6.873205,28.926829
3953,NaN,NaN,NaN,Zambia,2020-10-09 04:23:59,-13.133897,27.849332,15301,335,14365,601.0,Zambia,83.230182,2.189399
3954,NaN,NaN,NaN,Zimbabwe,2020-10-09 04:23:59,-19.015438,29.154857,7951,229,6446,1276.0,Zimbabwe,53.495519,2.880141